/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:0f0ee199-5d7a-410d-ba2a-920d7fde11fb",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_FsUj40Wy9",
    "aws_user_pools_web_client_id": "7clren0tribit0s4rlo49qb2o",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://3tmjoz7dvrg5hbh6wdnxadxqca.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-atvrfxloyfah5ighcsmasure3a",
    "aws_user_files_s3_bucket": "aruna-storage203345-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
